# fly.toml app configuration file generated for warex on 2023-11-20T20:57:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "warex"
primary_region = "ams"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "warex.fly.dev"
  PORT = "8082"

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
